# Generated by Django 4.0.3 on 2023-09-06 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_status_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
